# -----------------------------------------------------------------------------
# AWS CodeBuild Build Specification
# This file defines the build phases for deploying the Node.js application
# -----------------------------------------------------------------------------

version: 0.2

env:
  secrets-manager:
    # Fetch all secrets from Secrets Manager
    # The secret ARN is passed as SECRETS_ARN environment variable from CodeBuild
    APP_SECRETS: ${SECRETS_ARN}

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --production

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Environment: $ENVIRONMENT"
      # Parse secrets and create .env file
      - |
        echo "Creating .env file from Secrets Manager..."
        # Get the secret value and parse JSON to create .env
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRETS_ARN --query SecretString --output text)
        # Convert JSON to .env format
        echo "$SECRET_JSON" | python3 -c "
        import json, sys
        secrets = json.load(sys.stdin)
        for key, value in secrets.items():
            print(f'{key}={value}')
        " > .env
        echo "Environment variables loaded successfully"

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Preparing deployment package..."
      # Create deployment directory
      - mkdir -p deploy
      - cp -r src deploy/
      - cp package.json deploy/
      - cp package-lock.json deploy/
      - cp .env deploy/
      - cp -r node_modules deploy/

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Deployment package ready"

artifacts:
  files:
    - '**/*'
  base-directory: deploy
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
